spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Blogweb
    username: postgres
    password: Kevine@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

logging:
  level:
    com.blog: DEBUG
    org.hibernate.SQL: DEBUG
