spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test
    username: postgres
    password: Kevine@123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    com.blog: INFO
