spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_prod
    username: postgres
    password: Kevine@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    com.blog: INFO
    root: WARN
