spring:
  profiles:
    active: dev
  application:
    name: blogging-platform
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
    schema:
      printer:
        enabled: true

server:
  port: 8080
